= My EJB full

== Key work for continue researching

[source, code]
----
public class ObjectMapperContextResolver implements ContextResolver<ObjectMapper>
----

== Create project

[source, code]
----
	Create maven project with type - maven-archetype-quickstart <1>
	After that change packaging of project to "pom" type <2>
	Add config properties project.build.sourceEncoding, maven.compiler.source, maven.compiler.target 1.7 <3>
	remove project(not delete physical folder) and go to directory project folder delete all except "src, and pom file" <4>
	Import maven project again <5>
	Create ear module project with type is "maven-archetype-quickstart" <6>
	Create ejb module project with type is "maven-archetype-quickstart" <7>
	Create war module project with type is "maven-archetype-webapp" <7>
	Remember packaging correct with type
----

*Plugin package ejb and ear project*

[source, xml]
----
<!-- plugin package for ear --> <1>
<plugin>
	<artifactId>maven-ear-plugin</artifactId>
	<version>2.9.1</version>
	<configuration>
	    <defaultLibBundleDir>lib/</defaultLibBundleDir>
	    <modules>
	        <webModule>
	            <groupId>mhdanh.api</groupId>
	            <artifactId>ejbdoc-war</artifactId>
	            <contextRoot>/dejb</contextRoot>
	        </webModule>
	        <!-- can add more -->
	    </modules>
	</configuration>
</plugin>

<!-- plugin package verion ejb --> <2>
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-ejb-plugin</artifactId>
	<version>2.5.1</version>
	<configuration>
  		<ejbVersion>3.0</ejbVersion>
	</configuration>
</plugin>
----


[IMPORTANT]
Remember add *@ApplicationPath* and extends Application for config root api

[IMPORTANT]
*@PersistenceUnit* used for EntityManagerFactory, *@PersistenceContext* used for EntityManager

*QUERY SELECT LIST*

[source, java]
----
String str = "SELECT room FROM RoomEntity room WHERE room.name = :name";
Query query = entityManager.createQuery(str, RoomEntity.class);
query.setParameter("name", "admin");
return query.getResultList(); <1>
----

*QUERY UPDATE/DELETE*

[source, java]
----
String str = "DELETE FROM RoomEntity room where room.name = :name";
String str = "UPDATE RoomEntity room SET room.name = 'okman' where room.name = :name";
Query query = entityManager.createQuery(str);
query.setParameter("name", "room 1");
return query.executeUpdate();
----


== CDI example

*@Alternative*

we apply @Alternative for each implatation and config which implematation can be use in which evironment
in beans.xml in webapp folder. remember put it in webapp

[source, xml]
----
<beans xmlns="http://java.sun.com/xml/ns/javaee"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/beans_1_0.xsd">

    <alternatives>
        <class>mhdanh.ejbdoc.bussiness.LocalValidateBusinessImpl</class>
    </alternatives>

</beans>
----

== Persistent file

* We create datasource on wildfly and use it in persistent file, and also have jndi binding

[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.0"
	xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd">
	<persistence-unit name="ejb_pu" transaction-type="JTA">
		<provider>org.hibernate.ejb.HibernatePersistence</provider>
		
		<jta-data-source>ejbdoc</jta-data-source>
		
		<properties>
<!-- 			Bind entity manager factory to JNDI at java:jboss/myEntityManagerFactory -->
			<property name="jboss.entity.manager.jndi.name" value="java:/ejbdoc_em" />
			<property name="hibernate.dialect" value="org.hibernate.dialect.PostgreSQLDialect"></property>
			<property name="hibernate.connection.driver_class" value="org.postgresql.Driver" />
			<property name="hibernate.hbm2ddl.auto" value="create" />
			<property name="hibernate.show_sql" value="true" />
		</properties>
	</persistence-unit>
	
	<persistence-unit name="ejb_pu_tmp" transaction-type="JTA">
		<jta-data-source>ejbdoc_tmp</jta-data-source>
		<exclude-unlisted-classes>false</exclude-unlisted-classes>
	</persistence-unit>
</persistence>
----

== Lookup JNDI

[source, java]
----
@ForHeaderDB
@Produces
EntityManager getEm() throws NamingException {
	Context ctx = new InitialContext();
    return (EntityManager) ctx.lookup("java:/ejbdoc_em_tmp");
}
----

== Using Interceptor

* create simple interceptor

[source, java]
----
public class MyInterceptor { <1>
	
	@AroundInvoke
	public Object printLog(InvocationContext context) throws Exception {
		Logger.getLogger("Okman").log(Level.INFO, "Before execute method ");
		Object result = context.proceed();
		Logger.getLogger("Okman").log(Level.INFO, "After execute method ");
		return result;
	}
	
}

@Interceptors(MyInterceptor.class) <2>
public Object saveRoom() {
	return roomBusiness.saveRoom();
}
----
<1> Create class interceptor
<2> Use it


* customer interceptor

[source, java]
----

@Inherited
@InterceptorBinding <0>
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface RequestVerify { <1>
	
}

@Interceptor
@RequestVerify
@Priority(Interceptor.Priority.APPLICATION) <3>
public class RequestVerifyInterceptor { <2>

	@AroundInvoke
	public Object checkRequest(InvocationContext context) throws Exception {
		
		Logger.getLogger("MyLog").log(Level.INFO, "Request Header information ID " + context.getTarget());

		Object target = context.getTarget();
		if(target instanceof RestResource) {
			RestResource restResource = (RestResource) context.getTarget();
			HttpServletRequest request = restResource.getServletRequest();
			String id = request.getHeader("My_ID");
			Logger.getLogger("MyLog").log(Level.INFO, "My ID " + id);
			
			if("123".equals(id)) {
				throw new Exception("Plz dont go further " + id);
			}
		}
		Object obj = context.proceed();
		return obj;
	}
	
}
----
<0> It very important that, which process have interceptor
<1> Create new annotation
<2> Create class interceptor
<3> Enable interceptor in application

[IMPORTANT]
We should create parent restResource to get httpServletRequest and other resource must extent this class

[source, java]
----
@RequestScoped
public class RestResource {

	@Context
	private HttpServletRequest servletRequest;

	public HttpServletRequest getServletRequest() {
		return servletRequest;
	}

}
----	


*Enable interceptor in application in beans.xml*

[source, xml]
----
<beans xmlns="http://java.sun.com/xml/ns/javaee"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/beans_1_0.xsd">

    ...

	<interceptors>
    	<class>mhdanh.ejbdoc.interceptor.RequestVerifyInterceptor</class>
    </interceptors>
    
</beans>
----

== Add Swagger for Rest API

* Require pom file library

[source, xml]
----
	<!-- Swagger -->
	<dependency>
		<groupId>io.swagger</groupId>
		<artifactId>swagger-jaxrs</artifactId>
		<version>1.5.5</version>
	</dependency>
----

* Config swagger

[source, java]
----
@ApplicationPath("api")
public class AppConfig extends Application {
	
	<1>
	public AppConfig(){
		// init for swagger
		BeanConfig beanConfig = new BeanConfig();
		beanConfig.setVersion("1.0");
		beanConfig.setTitle("Welcome to EJB DOC");
		beanConfig.setDescription("This is all api we create for test example");
		beanConfig.setSchemes(new String[] { "http", "https"});
		beanConfig.setBasePath("dejb/api");
		beanConfig.setResourcePackage("mhdanh.ejbdoc.resource");
		beanConfig.setScan(true);
	}
}
----
<1> Method constructor in appconfig rest to initilize swagger

* How to use swagger

[source, java]
----
@SwaggerDefinition(info = @Info(description = "This API will be used in LUZ finance projects at AxonIvy company", version = "V1.0.0", title = "Finance REST API", termsOfService = "private"), schemes = {
		SwaggerDefinition.Scheme.HTTP, SwaggerDefinition.Scheme.HTTPS })
@Api(value = "rooms") // Swagger annotation
@Path("rooms")
@RequestScoped
public class RoomResource extends RestResource{ <1>
.....

@GET
@Path("{id}")
@ApiOperation(value = "Get offer by id", notes = "Get offer by id")
@ApiResponses(value = {
        @ApiResponse(code = HttpServletResponse.SC_NOT_FOUND, message = Constants.ENTITY_NOT_FOUND),
        @ApiResponse(code = HttpServletResponse.SC_OK, message = Constants.MSG_OK, response = Offer.class)})
public Response findOfferById(@PathParam("id") long id) { <2>
	Offer offer = offerService.findOfferById(id);
	return responseWithEntityOr404(offer);
}
----
<1> Defined in rest resource
<2> Add description on method in rest resource

* apply swagger ui

[source, html]
----
https://github.com/swagger-api/swagger-ui <1>
----
<1> access that link and download source web app and include in /webapp/index of project

* Config swagger url and customer additional field

[source, js]
----
$(function () {
      var url = window.location.search.match(/url=([^&]+)/);
      if (url && url.length > 1) {
        url = decodeURIComponent(url[1]);
      } else {
        url = window.location.protocol + "//" + window.location.host + "/luzfin_finance/api/swagger.json"; <1>
      }

      // Pre load translate...
      if(window.SwaggerTranslator) {
        window.SwaggerTranslator.translate();
      }
      window.swaggerUi = new SwaggerUi({
        url: url,
        validatorUrl : null,
        dom_id: "swagger-ui-container",
        supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
        onComplete: function(swaggerApi, swaggerUi){
          if(window.SwaggerTranslator) {
            window.SwaggerTranslator.translate();
          }
          $('pre code').each(function(i, e) {
            hljs.highlightBlock(e)
          });
          
          addCompanyPanel(); <2>
        },
        onFailure: function(data) {
          log("Unable to Load SwaggerUI");
        },
        docExpansion: "none",
        jsonEditor: false,
        apisSorter: "alpha",
        defaultModelRendering: 'schema',
        showRequestHeaders: false
      });

      window.swaggerUi.load();
      
      function addCompanyPanel() {
    	  var elementCompany = '<form>' +
    	  	'<label for="COMPANY_ID" style="font-weight: bold;">Company ID: </label>' + 
    	  	'<input id="COMPANY_ID" class="parameter" placeholder="Company ID" name="COMPANY_ID" type="text"/>' +
    	  	'</form>';
    	  $('#api_info').after(elementCompany);
    	  triggerCompany();
      }
      
      function triggerCompany() {
    	// add a new SwaggerClient.ApiKeyAuthorization when the api-key changes in the ui.
   	    $('#COMPANY_ID').change(function() {
   	    	var key = $('#COMPANY_ID')[0].value;
   	        if(key && key.trim() != "") {
   	           window.swaggerUi.api.clientAuthorizations.add("COMPANY_ID", new SwaggerClient.ApiKeyAuthorization("COMPANY_ID", key, "header"));
               console.log("added company id: " + key);
   	        }
   	    })
   	}

      function log() {
        if ('console' in window) {
          console.log.apply(console, arguments);
        }
      }
  });
----
<1> Change url accordding to your url
<2> Add additional field for execute swagger
